-- TRIGGER CANNOT BE APPLIED ON TEMPERORY TABLE;
 DROP TRIGGER update_user_date;
 SHOW VARIABLES LIKE '%AUTOCOMMIT%';
 
 UPDATE EMP1
SET SAL=100 WHERE EMPNO=7369; 
ROLLBACK;
DELIMITER # 
create trigger update_user_date
BEFORE -- IF I USE AFTER THEN ERROR COME B/Z AFTER ACTUAL UPDATE  IN 5 TO 6
UPDATE--  THAT PARTICULAR ONLY  RECORD IS IN LOCKING CONDITION AND NOT ROW LEVEL LOCKING B/Z 
ON EMP1 -- THERE IS PRIMARY KEY SO TO AVOID IT I USE TRIGGER BEFORE ACTUAL UPDATE HAPPEN TO AVOID LOCKING IN NEW ARRAY OR KEYWORD NEW ALLVALUES WHICH WILL
FOR EACH ROW-- BE UPDATED ARE STORED SO NO NEED TO WRITE LIKE  UPDATE EMP1 SET NEW.last_updated_by= CURRENT USER() 
BEGIN-- INSTEAD YOU CAN WRITE DIRECT  SET NEW.last_updated_by= CURRENT USER()  B/Z IT KNOW SETTING IS DONE SAME TABLE

SET NEW.last_updated_by=current_user();
SET NEW.last_updated_date=SYSDATE(); 

END #

SELECT * FROM EMP1;



CREATE  TABLE EMP1
LIKE EMP;

DROP TEMPORARY TABLE EMP1;

INSERT INTO EMP1
SELECT * FROM EMP;

SELECT * FROM EMP1;

ALTER TABLE EMP1
ADD COLUMN last_updated_by  VARCHAR(500);

ALTER TABLE EMP1
ADD COLUMN last_updated_date DATE;


0104	18:11:45	UPDATE EMP1
 SET SAL=100 WHERE EMPNO=7369	Error Code: 4048. Invalid target for assignment 
 in INSERT or UPDATE statement 'NEW.last_updated_by'.	0.203 sec
 0	107	18:18:13	UPDATE EMP1
 SET SAL=100 WHERE EMPNO=7369	Error Code: 4048. Invalid target for assignment
 in INSERT or UPDATE statement 'OLD.last_updated_by'.	0.047 sec
 
 0	110	18:25:30	UPDATE EMP1
 SET SAL=100 WHERE EMPNO=7369	Error Code: 4048. Invalid target for assignment
 in INSERT or UPDATE statement 'NEW.last_updated_by'.	0.047 sec
 
 -- IT MEANS WE CANNOT UPDATE SAME RECORD IN TRIGGER ON THAT ALREADY UPDATE IS HAPPENEING 
 -- OUTSIDE TRIGGER BOTH BELOW WRONG 


 -- INSIDE TRIGGER
 
 /* UPDATE EMP1
 SET NEW.last_updated_by=current_user() WHERE EMPNO=OLD.EMPNO;
 UPDATE EMP1
 SET NEW.last_updated_date=SYSDATE() WHERE EMPNO=OLD.EMPNO;*/
 
 0	119	18:36:31	create trigger update_user_date
 AFTER 
 UPDATE
 ON EMP1
 FOR EACH ROW
 BEGIN 

 
 Error Code: 1362. Updating of NEW row is not allowed in after trigger	0.000 sec
 
 SET NEW.last_updated_by=current_user();-- WHERE EMPNO=OLD.EMPNO;
 
 SET NEW.last_updated_date=SYSDATE(); -- WHERE EMPNO=OLD.EMPNO;
 
 
 AFTER TIMING  DURING UPDATE SAME TABEL WE CAN ONLY OLD DATA SO ABOVE ARE WRONG
 
 COREEE