DROP PROCEDURE EVEN_ODD
DELIMITER #
create procedure even_odd(NUM INT)
BEGIN
IF(MOD(NUM,2)=0) THEN
SELECT 'NUMBER IS EVEN'AS 'NUM';
ELSE 
SELECT 'NUMBER IS ODD'AS 'NUM';
END IF;
END #

CALL EVEN_ODD(233)
