 DROP PROCEDURE letter_digit;
set @s_var=(2);-- session variable DATATYPE SET AS VALUE
call letter_digit(@s_var)

DELIMITER #
create procedure letter_digit(p_ch VARCHAR(1))
BEGIN
IF (ASCII(p_ch) BETWEEN 48 AND 57) THEN
SELECT 'IT IS DIGIT' AS 'CHARACTER NATURE';
ELSEIF((ASCII(p_ch) BETWEEN 65 AND 90) OR (ASCII(p_ch) BETWEEN 97 AND 122) )THEN
SELECT 'IT IS LETTER'AS 'CHARACTER NATURE';
ELSE
SELECT 'SPECIAL CHARACTER'AS 'CHARACTER NATURE';

END IF;
END#